//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDTDD_FPT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Exports = new HashSet<Export>();
            this.Imports = new HashSet<Import>();
            this.Orders = new HashSet<Order>();
            this.TimeBooks = new HashSet<TimeBook>();
        }
    
        public string StaffId { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public string UserRole { get; set; }
        public string UserId { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool Gender { get; set; }
        public int MonthlySalary { get; set; }
    
        public virtual ICollection<Export> Exports { get; set; }
        public virtual ICollection<Import> Imports { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<TimeBook> TimeBooks { get; set; }
    }
}
